server:
  bind:
    host: 0.0.0.0
    port: 80
  cors: true
  encoding: utf-8
  gzip: false
  language: en-US
  limit: 10
  manager:
    connection: /tmp/pygeoapi-process-manager.db
    name: TinyDB
    output_dir: /tmp/
  map:
    attribution: <a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia
      maps</a> | Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap
      contributors</a>
    url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
  mimetype: application/json; charset=UTF-8
  ogc_schemas_location: /schemas.opengis.net
  pretty_print: true
  url: http://localhost:5000
logging:
  level: DEBUG
  logfile: /dev/stdout
metadata:
  contact:
    address: Mailing Address
    city: City
    country: Canada
    email: you@example.org
    fax: +xx-xxx-xxx-xxxx
    hours: Hours of Service
    instructions: During hours of service.  Off on weekends.
    name: Doe, John
    phone: +xx-xxx-xxx-xxxx
    position: Lead Dev
    postalcode: Zip or Postal Code
    role: pointOfContact
    stateorprovince: Administrative Area
    url: Contact URL
  identification:
    description: pygeoapi provides an API to geospatial data
    keywords:
    - geospatial
    - data
    - api
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    title: pygeoapi directed
    url: https://github.com/geopython/pygeoapi
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: pygeoapi Development Team
    url: https://pygeoapi.io
resources:
  climada-simple-example-denmark-process:
    processor:
      name: directed_pygeoapi_processes.climada.SimpleExampleDenmarkProcessor
    type: process
